project:
  type: "website"

website:
  title: "GeoJupyter Pitch"
  site-url: "https://SchmidtDSE.github.io/geojupyter-pitch"
  repo-url: &repo-url "https://github.com/SchmidtDSE/geojupyter-pitch"
  repo-actions: ["edit", "issue"]
